[pytest]
addopts = --alluredir=allure-results -v --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    auth: Authorization tests
    constructor: Constructor tests